### ISSUE TITLE
Merges failing builds

### ISSUE THREAD

**Issue by travi** [kkemple/greenkeeper-keeper#13]
Great idea putting a tool like this together. I finally got around to deploying my own instance this weekend, but I'm not seeing the behavior expected. It seems to be merging greenkeeper PRs even when a build fails. 

Have I missed something that I should have configured? Should I expect it to make sure that all checks pass, or does it only look at specific checks? In this case, it was a [Travis failure](https://github.com/travi/any/pull/49).

**Comment by kkemple** [comment]
It should be failing for builds that fail, that is the behavior I am seeing, can I ask how long ago you forked and do you have the latest on master? If so, you should see in the logs what is happening.

If you do have the latest then we can continue to debug.

**Comment by travi** [comment]
I forked on Saturday. You can find my fork [here](https://github.com/travi/greenkeeper-keeper). I've got it wired up to Heroku to deploy as master of my fork gets updated.

I hadn't dug into the code yet, but looking at the logs, I recognize the `good` output. I'm a big fan of hapi, so nice to see this tool using it :)

From the logs, I see that the state is marked as `error`, but [the code](https://github.com/travi/greenkeeper-keeper/blob/master/plugins/keeper/index.js#L41-L42) appears to only be checking for `failure` and `pending`. I think `error` simply needs to added to the list of statuses that should be rejected.

Want me to submit a PR for the addition, or would it be simpler for you to take care of it?

**Comment by kkemple** [comment]
no please do! would love the contribution! unless you don't have the time then I will gladly do it myself

**Comment by travi** [comment]
Sure thing. I should be able to get to it by tonight. 

Would you rather I add a check for `error`, or instead explicitly check for the success case, rejecting if not pending or success?

**Comment by kkemple** [comment]
totally missed your comment, sorry about that. what you had was good. the reason we do separate check for pending is we have to keep checking back until all the statuses are finished or until the first one fails. if we only checked for success and not pending we wouldn't know if all the jobs were done or not (i hope I understood your question correctly :smile:)

**Comment by travi** [comment]
yeah, i understood the `pending` part. my question was more about looking for a lack of `failure` and `error` vs presence of `success` in case there were other statuses that we were still missing that should be rejected. 

once i looked at making the actual fix, i realized that you needed to loop through all of the checks rather than looking at a top level status, so this was a far simpler change for now.

thanks for accepting the change :)

**Comment by kkemple** [comment]
thanks for submitting it! :tada:
