### ISSUE TITLE
publish as an npm package

### ISSUE THREAD

**Issue by travi** [kkemple/greenkeeper-keeper#23]
would it make sense to publish the hapi plugin as a consumable package through npm? that way, when you publish new versions, greenkeeper could alert me with a PR rather than needing to keep my fork up to date. a little meta, but i see no reason why it shouldn't work.

thoughts?

**Comment by kkemple** [comment]
i don't see any reason that the hapi plugin can't be a stand alone module, i will work on breaking this out over the weekend

**Comment by travi** [comment]
awesome. thanks!

**Comment by kkemple** [comment]
this is going to be done next week

**Comment by travi** [comment]
i've started a repo for this [here](https://github.com/greenkeeper-keeper/hapi-greenkeeper-keeper). if you decide that you still don't want to go the organization route, it can always be transferred.

@kkemple i've kept you as the author in the package file and in the license file, but added myself as a maintainer.

for now, my plan is to pull the existing plugin over in its current state, with https://github.com/kkemple/greenkeeper-keeper/pull/49 included. once it is published to npm in that form, i'll start getting tests wrapped around it with the intent of releasing v1.0.0 that includes fixes for some of the remaining issues that have been logged. #46 and #27 will probably make sense to be breaking changes, so it would be good to at least handle those pre-v1.0.0

once that is available, i hope to use a combination of [your bot](https://github.com/greenkeeper-keeper-bot) and [semantic-release](https://github.com/semantic-release/semantic-release) to fully automate future releases. would you be ok with that bot being used for this? i think that makes the most sense to me

**Comment by travi** [comment]
v0.0.1 has been [published to npm](https://www.npmjs.com/package/hapi-greenkeeper-keeper) to match what the plugin was [currently marked as](https://github.com/kkemple/greenkeeper-keeper/blob/517c2f2a7f2a93a2a9c3ae8b8a57b4668f1364d8/plugins/keeper/index.js#L138), i'll get a PR together soon back to this project to consume the plugin.
