### ISSUE TITLE
update to work with the new version (github integration)

### ISSUE THREAD

**Issue by travi** [kkemple/greenkeeper-keeper#38]
the PR now comes from [greenkeeper](https://github.com/integration/greenkeeper) instead of `greenkeeper-bot`. would that be the only update that is needed to get this working again?

**Comment by travi** [comment]
it looks like the bot now automatically closes the branch almost immediately after the PR is merged, so that could probably be trimmed out as well

**Comment by kkemple** [comment]
hey @travi, im going to fix debugging on this next week, then we can inspect the GH responses better. also, im going to review API docs this week

**Comment by travi** [comment]
i think [my PR](https://github.com/kkemple/greenkeeper-keeper/pull/41) should handle this one, so i think we are good to go on this part once your schedule frees up a bit

**Comment by travi** [comment]
@kkemple any objection to the PR getting merged in at this point?

**Comment by kkemple** [comment]
not at all, and since i haven't been able to get to this i am reassessing my decision to not move this to an org or let you take over the project by adding you as a maintainer or letting you have the repository

I wish i had more time for this right now but I just don't and I would love for it to work again :smile:

**Comment by travi** [comment]
i can understand being busy, especially around this time of year. my team is looking to make pretty heavy use of this as a tool, so i should be able to justify investing in continuing to evolve it. 

i don't want to step on your toes with your project. i know you gave me access, but i didnt want to merge this into your project without your involvement. if you were comfortable elevating things into the org i invited you to, it would make me more comfortable making contributions when you may not have the bandwidth. being able to move changes forward with shorter delays would certainly be comforting to my team as well. either way, i'd still want to coordinate with you whatever arrangement makes the most sense for the project that you started.

with this merged in, i plan to at least bandaid #45 and #47 because they have bitten me a few times, but then thought i'd start to tackle test driving #23. that one ends up being a separate repo and essentially going over everything in the hapi plugin again. so that would be a great point to have a solid plan for where we want the repo to live. if it makes sense for that to be in the org, we could move the other pieces as they make sense.

i'm traveling for the holidays, so i probably wont get a chance to tackle any of this in the very near term, but am happy to discuss how you'd like to see the project continue forward.
