### ISSUE TITLE
consider moving to an organization?

### ISSUE THREAD

**Issue by travi** [kkemple/greenkeeper-keeper#40]
Greenkeeper has become an indispensable part of my workflow and I think their GitHub integration has been a big step in a good direction. Greenkeeper-keeper was a great help to keeping the PRs from greenkeeper manageable before the switch to be an integration, and the impact of greenkeeper-keeper not working with the integration has been large.

I'd like to help out getting this back a state that works. #38 is really important, but I haven't seen any response on it yet. I'm sure you're busy and just haven't had a chance to take a serious look at it, but getting no response makes me hesitant to dig in and try to a change for fear that it wouldn't get attention to be merged. I'd also be really interested in helping with #23, which I think would make it easier to maintain, but also greatly improve the ability to consume it.

So with all that context, would you be open to additional maintainers? I think moving this project and what would result from #23 to a `greenkeeper-keeper` org would make a lot of sense to keep the two grouped, but also involve additional maintainers like myself. You even already a nice logo for the org.

Even if you don't want to go as far as creating an org, I'm interested in your suggestions on the best approach to get the two issues mentioned above moving forward. I'm probably better equipped to tackle #23 than #38, but I'm hesitant to tackle #23 first since I've enabled the integration for all the projects that I have access to, which would make it hard to confirm the changes for #23.

**Comment by travi** [comment]
not to pressure in this direction, but i did reserve https://github.com/greenkeeper-keeper and invited you in case it might be a move you'd be interested in making

**Comment by kkemple** [comment]
Hey @travi, sorry for the delayed response on this! I don't see the benefit in adding this under an org, I am willing to open up to contributors as needed but going full org seems too much.

I have been crazy busy with work as our season is wrapping up in 5 days, so after that I will be investing heavy time into my OS projects.

Let's regroup in a week and get it back in tiptop shape, in the mean time I will add you as a contributor but lets refrain from anything going into master this week.

**Comment by travi** [comment]
no worries. i totally understand being swamped, so hopefully my PR on getting the integration working again will be helpful.

as far as the organization goes, that decision is obviously completely up to you. i normally don't like to grant others access to my personal projects. as a consumer, i also find it helpful when related projects are grouped together rather than being under someone's personal account. so, I thought once the hapi plugin was published separately from the app implementation, it might help guide new users a bit. no worries if you don't want to go that far though.

**Comment by travi** [comment]
also, thanks for the add on the project. no worries about holding off on merging things in. i would certainly not want to be too aggressive on pushing things into your project. i would still plan to make any contributions as PRs and get your input before merging unless you set a different expectation.
